# -*- coding: utf-8 -*-
"""extractTrain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxAH3mQKBlmbyKzlwBEf_VbST4twQUDk
"""

import os
import subprocess
def make_dir(pth):
    if not os.path.exists(pth):
        os.mkdir(pth)
def f(start,idx):#creates train_idx folder(with 50 files)
    xv, yv = '/media/Data2/srivinod/train/X/X', '/media/Data2/srivinod/train/Y/Y'
    make_dir('/media/Data2/srivinod/train'+str(idx))
    make_dir('/media/Data2/srivinod/train'+str(idx)+'/X')
    make_dir('/media/Data2/srivinod/train'+str(idx)+'/Y')
    xf1, yf1 = '/media/Data2/srivinod/train'+str(idx)+'/X/X', '/media/Data2/srivinod/train'+str(idx)+'/Y/Y'
    for i in range(start + 50*(idx-1),start +50*idx):
        make_dir(xf1+str(i))
        cmd = 'ffmpeg -i \"{}\" -vf scale=128:128 \"{}/image_%05d.png\"'.format(xv+str(i)+'.mp4', xf1+str(i))
        print(subprocess.call(cmd, shell=True), end = ',')
        if not os.path.exists(yf1+str(i)):
            make_dir(yf1+str(i))
        cmd = 'ffmpeg -i \"{}\" -vf scale=128:128 \"{}/image_%05d.png\"'.format(yv+str(i)+'.mp4', yf1+str(i))
        print(subprocess.call(cmd, shell=True), end = ',')
        print(i)

f(10000, 10)
