# -*- coding: utf-8 -*-
"""EXTRACT_TRAIN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRi6JtjmVEwHCrBjPkDao-9A06-PLIiZ
"""

import os
import subprocess
def make_dir(pth):
    if not os.path.exists(pth):
        os.mkdir(pth)
def f():#creates train_idx folder(with 50 files)
    xv, yv = '/media/Data2/srivinod/train/X/X', '/media/Data2/srivinod/train/Y/Y'
    make_dir('/media/Data2/srivinod/train2')
    make_dir('/media/Data2/srivinod/train2'+'/X')
    make_dir('/media/Data2/srivinod/train2'+'/Y')
    xf1, yf1 = '/media/Data2/srivinod/train2'+'/X/X', '/media/Data2/srivinod/train2'+'/Y/Y'
    for i in range(10000,20000):
        # make_dir(xf1+str(i))
        cmd = 'ffmpeg -i \"{}\" -ss 00:00:01 -vframes 1 -vf scale=128:128 \"{}.png\"'.format(xv+str(i)+'.mp4', xf1+str(i))
        subprocess.call(cmd, shell=True)
        # if not os.path.exists(yf1+str(i)):
        #     make_dir(yf1+str(i))
        cmd = 'ffmpeg -i \"{}\" -ss 00:00:01 -vframes 1 -vf scale=128:128 \"{}.png\"'.format(yv+str(i)+'.mp4', yf1+str(i))
        subprocess.call(cmd, shell=True)
        if i%1000==0:
            print(i+1)



f()